# 定义全局日志配置
x-logging: &default-logging
  # 指定服务容器的日志记录驱动程序。默认值和可用值因平台而异。
  driver: json-file
  # 驱动程序特定选项作为键值对。
  options:
    # 单个日志文件最大 10MB
    max-size: "16m"
    # 保留最多 3 个日志文件
    max-file: "8"
    # 是否压缩轮转的日志文件
    compress: "true"

services:
  turing-db:
    # 定义服务的日志配置。
    logging: *default-logging
  turing-keycloak:
    # 定义服务的日志配置。
    logging: *default-logging
  turing-redis:
    # 定义服务的日志配置。
    logging: *default-logging
  turing-backend:
    # 定义服务的日志配置。
    logging: *default-logging
  turing-nginx:
    # 定义服务的日志配置。
    logging: *default-logging
  turing-portainer:
    # 定义服务的日志配置。
    logging: *default-logging