server:
  port: 9443
  ssl:
    bundle: demo-authorizationserver
    client-auth: want

spring:
  config:
    # 导入额外的配置数据。
    import: optional:file:.env[.properties]
  datasource:
    # 数据库的 JDBC URL。
    url: jdbc:postgresql://${HOST}:5432/turing
    # 数据库的登录用户名。
    username: turing
    # 数据库的登录密码。
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/oauth2-authorization-consent-schema.sql
        - classpath:db/oauth2-authorization-schema.sql
        - classpath:db/oauth2-registered-client-schema.sql
  #      platform: postgres
  ssl:
    bundle:
      jks:
        demo-authorizationserver:
          key:
            alias: demo-authorizationserver-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
